config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :items do
    resources :orders
  end
  resources :orders

  resources :orders do
    resources :orderitems
  end

  post 'add_to_cart' => 'cart_items#add_to_cart', as: :add_to_cart
  post 'update_item_quantity' => 'cart_items#update_item_quantity', as: :update_item_quantity

  get '/login'     => 'sessions#new'
  post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/checkout' => 'orders#checkout', as: :checkout
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :orderitems
  has_many :orders, through: :orderitems
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :orderitems
  has_many :items, through: :orderitems
  has_one :orderstatus
end

app/models/orderitem.rb
class Orderitem < ActiveRecord::Base
  belongs_to :order
  belongs_to :item
end

app/models/orderstatus.rb
class Orderstatus < ActiveRecord::Base
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :initialize_orderitem

  helper_method :current_user, :items_count

  def initialize_orderitem
    @orderitem = Orderitem.new
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_order
    @current_order ||= Order.find_by(id: session[:current_order_id])
  end

  def load_cart
    @cart ||= session[:cart]
  end


  def items_count
    @items_count = session[:cart].values.sum
  end

  before_action :load_cart

  def order_status
    @order = Order.new
    @order.user_id = current_user.id
    @order.status = 1
    @order.save
    session[:current_order_id] = @order.id
    return session[:current_order_id]
  end


  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def add_to_cart
    session[:cart][params[:id]] ||= 0
    session[:cart][params[:id]] = session[:cart][params[:id]] += 1
    redirect_to :back
  end

  def update_item_quantity
    session[:cart][params[:id]] = params[:id]
    redirect_to :back
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
    # @items_count = items_count
  end

  def show
    @item = Item.find(params[:id])
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    item_ids = session[:cart].keys
    @item_values = session[:cart].values
    binding.pry
    items = item_ids.find_all { |item| Item.find(item) }
    @itemlist = Item.find(items)
    @order = Order.new

  end

  def create

    @item = Item.find(params[:item_id])
    if session[:current_order_id] == nil
      order_status
      if @order.save
        @orderitem = Orderitem.new(orderitem_params)
        @orderitem.order_id = session[:current_order_id]
        @orderitem.item_id = @item.id
        @orderitem.selling_price = @item.marked_price
        @orderitem.save

        redirect_to item_path(@item)
      else
        render :new
      end

    elsif session[:current_order_id] != nil
      @orderitem = Orderitem.new(orderitem_params)
      @orderitem.order_id = session[:current_order_id]
      @orderitem.item_id = @item.id
      @orderitem.selling_price = @item.marked_price
      @orderitem.save

      redirect_to item_path(@item)

    end
  end

  def edit
    @order = Order.find(current_order)
    @orderitem = @order.orderitems
  end

  def update
    require 'pry'; binding.pry
    @order = Order.find(current_order)
      # @orderitem = @order.orderitems

      @order.orderitems.each do |orderitem|
        @orderitem = orderitem
        # @orderitem.update(orderitem_params)
      end


    if @orderitem.update(orderitem_params)
         redirect_to items_path, notice: 'Comment was successfully updated.'
    else
      render :edit

    end
   end




  def checkout
    session[:cart] = nil
    redirect_to items_path
  end

private
    def order_params
      params.require(:order).permit(:total_price)
    end

    def orderitem_params
      params.require(:orderitem).permit(:selling_quantity)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:login][:email])

    if user && user.authenticate(params[:login][:password])
      session[:user_id] = user.id.to_s
      redirect_to items_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create

    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id.to_s
      redirect_to users_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<h1>Cart ID <%= @order.id %></h1>
<!-- <ul>
    <% @order.orderitems.each do |orderitem| %>
    <li><%= orderitem.order_id %> </li>
    <li><%= orderitem.item.name %> </li>
    <li><%= orderitem.selling_quantity %> </li>
    <li><%= orderitem.selling_price %> </li>

    <% end %>

</ul> -->


<div class="container">
	<div class="row">
    <div class="col-xs-2">
    </div>
		<div class="col-xs-8">
			<div class="panel panel-info">
				<div class="panel-heading">
					<div class="panel-title">
						<div class="row">
							<div class="col-xs-6">
								<h5><span class="glyphicon glyphicon-shopping-cart"></span> Shopping Cart</h5>
							</div>
							<div class="col-xs-6">
                  <%= link_to "Continue Shopping", items_path, class:"glyphicon glyphicon-share-alt btn btn-primary btn-sm btn-block" %>
							</div>
						</div>
					</div>
				</div>
				<div class="panel-body">
          <% @order.orderitems.each do |orderitem| %>
					<div class="row">
						<div class="col-xs-2"><img class="img-responsive" src="http://placehold.it/100x70">
						</div>
						<div class="col-xs-4">
							<h4 class="product-name"><strong><%= orderitem.item.name %></strong></h4><h4><small>Product description</small></h4>
						</div>
						<div class="col-xs-6">
							<div class="col-xs-6 text-right">
								<h6><strong>$<%= orderitem.selling_price %>  <span class="text-muted">x</span></strong></h6>
							</div>
							<div class="col-xs-4">
                <!-- <%= orderitem.selling_quantity %> -->
								<input type="text" class="form-control input-sm" value="<%= orderitem.selling_quantity %>">
							</div>
							<div class="col-xs-2">
								<button type="button" class="btn btn-link btn-xs">
									<span class="glyphicon glyphicon-trash"> </span>
								</button>
							</div>
						</div>
					</div>

					<hr>
          <% end %>
					<div class="row">
						<div class="text-center">
							<div class="col-xs-9">
								<h6 class="text-right">Edit items?</h6>
							</div>
							<div class="col-xs-3">
								<button type="button" class="btn btn-default btn-sm btn-block">
								<%= button_to	"Update Cart", update_item_quantity_path %>
								</button>
							</div>
						</div>
					</div>
				</div>
				<div class="panel-footer">
					<div class="row text-center">
						<div class="col-xs-9">
							<h4 class="text-right">Total <strong>$50.00</strong></h4>
						</div>
						<div class="col-xs-3">
								<%= link_to "Checkout", checkout_path, class:"btn btn-success btn-block" %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/items/index.html.erb
<div class="container">
    <div class="row">
        <div class="row">
            <div class="col-md-9">
                <h3>
                    Products</h3>
            </div>
        </div>
        <div id="carousel-example" class="carousel slide hidden-xs" data-ride="carousel">
            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="item active">
                    <div class="row">
                      <% @items.each do |item| %>
                        <div class="col-sm-3">

                            <div class="col-item">
                                <div class="photo">
                                    <img src="http://placehold.it/350x260" class="img-responsive" alt="a" />
                                </div>
                                <div class="info">
                                    <div class="row">

                                        <div class="price col-md-6">
                                            <h5>
                                                <%= item.name %></h5>
                                            <h5 class="price-text-color">
                                                $<%= item.marked_price %></h5>
                                        </div>
                                        <div class="rating hidden-sm col-md-6">
                                            <i class="price-text-color fa fa-star"></i><i class="price-text-color fa fa-star">
                                            </i><i class="price-text-color fa fa-star"></i><i class="price-text-color fa fa-star">
                                            </i><i class="fa fa-star"></i>
                                        </div>
                                    </div>
                                    <div class="separator clear-left">
                                        <!-- <p class="btn-add"> -->
                                            <%= button_to "Add to Cart", add_to_cart_path(params: {id: item.id}), class:"fa fa-shopping-cart hidden-sm" %>
                                        <p class="btn-details">
                                            <i class="fa fa-list"></i><a href="#" class="hidden-sm">More details</a></p>
                                    </div>
                                    <div class="clearfix">
                                    </div>
                                </div>
                            </div>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
            </div>
    </div>
</div>

app/views/items/show.html.erb
<h1>Item</h1>
<ul>
    <li><%= @item.name %></li>
    <%= link_to "Make an Order", new_item_order_path(@item), method: :get %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoppingcart</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<!--   <% if current_user %>
  Logged in as: <%= current_user.first_name %>
  <%= link_to "Checkout", checkout_path %>
<% else %>
  <%= link_to 'Log In', login_path %>
  <%= link_to 'Sign Up', new_user_path %>
<% end %> -->
  <p> div box</p>
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#" class="navbar-brand">ShoppingCart</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><%= link_to "Products", items_path %></li>
                 <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">DropDown
                    <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Link 2</a></li>
                    </ul>
                 </li>
                 <% if session[:current_order_id] != nil %>
                <li><%= link_to "Checkout", checkout_path %></li>
                <% end %>
             </ul>
            <ul class="nav navbar-nav navbar-right">
                <% if current_user %>
                <li>Cart: <%= items_count %></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-user"></span> 
                        <strong><%=current_user.first_name %></strong>
                        <span class="glyphicon glyphicon-chevron-down"></span>
                    </a>
                <% else %>
                  <li><%= link_to "Sign Up", new_user_path, class:"glyphicon glyphicon-user"%></li>
                  <li><a href="#" data-toggle="modal" data-target="#loginModal"><span class="glyphicon glyphicon-log-in "></span> Login</a></li>
                <% end %>
                    <% if current_user %>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="navbar-login">
                                <div class="row">
                                    <div class="col-lg-4">
                                        <p class="text-center">
                                            <span class="glyphicon glyphicon-user icon-size"></span>
                                        </p>
                                    </div>
                                    <div class="col-lg-8">
                                        <p class="text-left"><strong><%= current_user.first_name %><%current_user.last_name %></strong></p>
                                        <p class="text-left small"><%= current_user.email %></p>
                                        <p class="text-left">
                                            <%= link_to "Check my Orders", orders_path, class:"btn btn-primary btn-block btn-sm" %>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="navbar-login navbar-login-session">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <p>
                                          <%= link_to 'Log Out', logout_path, method: :delete, class:"btn btn-danger btn-block" %>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                    <% end %>
                </li>
            </ul>
        </div>
    </div>
</div>

<form action="/login" method="post" id="loginForm">
    <div class="modal fade" id="loginModal" tabindex="-1">
        <div class="modal-dialog modal-sm">
          <div class="modal-content">
              <div class="modal-header">
                <%= form_for(:login) do |f| %>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Login</h4>
              </div>
              <div class="modal-body">
            <div class="form-group">
              <label class="control-label" for="email">User Email</label>
                <%= f.text_field :email, class: 'form-control', placeholder: "Enter your email"%>
            </div>
            <div class="form-group">
              <label class="control-label" for="password">Password</label>
              <%= f.password_field :password, class: 'form-control', placeholder: "Enter your password" %>
            </div>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                  <%= f.submit "Log in", class: "btn btn-primary" %>
              </div>
              <% end %>
          </div>
        </div>
    </div>
  </form>





<%= yield %>





</body>
</html>

app/views/orders/edit.html.erb
<h1>Edit Order</h1>
<%= form_for @order do |f| %>
  <% @orderitem.each do |orderitem| %>
   <%= fields_for orderitem do |u| %>

       <%= u.text_field :selling_quantity %>

    <% end %>
   <% end %>


  <div>
    <%= f.submit "Update Order" %>
  </div>
<% end %>

app/views/orders/index.html.erb
<h1>Orders</h1>
<ul>
  <% @orders.each do |order| %>
    <li><%= order.id %></li>
  <% end %>
</ul>

app/views/orders/new.html.erb
<h1>Cart ID <%= @order.id %></h1>
<!-- <ul>
    <% @order.orderitems.each do |orderitem| %>
    <li><%= orderitem.order_id %> </li>
    <li><%= orderitem.item.name %> </li>
    <li><%= orderitem.selling_quantity %> </li>
    <li><%= orderitem.selling_price %> </li>

    <% end %>

</ul> -->


<div class="container">
	<div class="row">
    <div class="col-xs-2">
    </div>
		<div class="col-xs-8">
			<div class="panel panel-info">
				<div class="panel-heading">
					<div class="panel-title">
						<div class="row">
							<div class="col-xs-6">
								<h5><span class="glyphicon glyphicon-shopping-cart"></span> Shopping Cart</h5>
							</div>
							<div class="col-xs-6">
                  <%= link_to "Continue Shopping", items_path, class:"glyphicon glyphicon-share-alt btn btn-primary btn-sm btn-block" %>
							</div>
						</div>
					</div>
				</div>
				<div class="panel-body">
          <% @itemlist.each do |orderitem| %>
					<% @item_values.each do |itemvalue| %>
					<div class="row">
						<div class="col-xs-2"><img class="img-responsive" src="http://placehold.it/100x70">
						</div>
						<div class="col-xs-4">
							<h4 class="product-name"><strong><%= orderitem.name %></strong></h4><h4><small>Product description</small></h4>
						</div>
						<div class="col-xs-6">
							<div class="col-xs-6 text-right">
								<h6><strong>$<%= orderitem.marked_price %>  <span class="text-muted">x</span></strong></h6>
							</div>
							<div class="col-xs-4">
								<!-- form tag -->
								<input type="text" class="form-control input-sm" value="<%=  itemvalue %>">
							</div>
							<div class="col-xs-2">
								<button type="button" class="btn btn-link btn-xs">
									<span class="glyphicon glyphicon-trash"> </span>
								</button>
							</div>
						</div>
					</div>

					<hr>
						<% end %>
          <% end %>
					<div class="row">
						<div class="text-center">
							<div class="col-xs-9">
								<h6 class="text-right">Edit items?</h6>
							</div>
							<div class="col-xs-3">
								<button type="button" class="btn btn-default btn-sm btn-block">
								<%= button_to	"Update Cart", update_item_quantity_path, method: :post, params: {items: { } } %>
								</button>
							</div>
						</div>
					</div>
				</div>
				<div class="panel-footer">
					<div class="row text-center">
						<div class="col-xs-9">
							<h4 class="text-right">Total <strong>$50.00</strong></h4>
						</div>
						<div class="col-xs-3">
								<%= link_to "Checkout", checkout_path, class:"btn btn-success btn-block" %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/orders/show.html.erb
<h1>Order ID <%= @order.id %></h1>
<!-- <ul>
    <% @order.orderitems.each do |orderitem| %>
    <li><%= orderitem.order_id %> </li>
    <li><%= orderitem.item.name %> </li>
    <li><%= orderitem.selling_quantity %> </li>
    <li><%= orderitem.selling_price %> </li>

    <% end %>

</ul> -->


<div class="container">
	<div class="row">
    <div class="col-xs-2">
    </div>
		<div class="col-xs-8">
			<div class="panel panel-info">
				<div class="panel-heading">
					<div class="panel-title">
						<div class="row">
							<div class="col-xs-6">
								<h5><span class="glyphicon glyphicon-shopping-cart"></span> Shopping Cart</h5>
							</div>
							<div class="col-xs-6">
                  <%= link_to "Continue Shopping", items_path, class:"glyphicon glyphicon-share-alt btn btn-primary btn-sm btn-block" %>
							</div>
						</div>
					</div>
				</div>
				<div class="panel-body">
          <% @order.orderitems.each do |orderitem| %>
					<div class="row">
						<div class="col-xs-2"><img class="img-responsive" src="http://placehold.it/100x70">
						</div>
						<div class="col-xs-4">
							<h4 class="product-name"><strong><%= orderitem.item.name %></strong></h4><h4><small>Product description</small></h4>
						</div>
						<div class="col-xs-6">
							<div class="col-xs-6 text-right">
								<h6><strong>$<%= orderitem.selling_price %>  <span class="text-muted">x</span></strong></h6>
							</div>
							<div class="col-xs-4">
                <!-- <%= orderitem.selling_quantity %> -->
								<input type="text" class="form-control input-sm" value="<%= orderitem.selling_quantity %>">
							</div>
							<div class="col-xs-2">
								<button type="button" class="btn btn-link btn-xs">
									<span class="glyphicon glyphicon-trash"> </span>
								</button>
							</div>
						</div>
					</div>

					<hr>
          <% end %>
					<div class="row">
						<div class="text-center">
							<div class="col-xs-9">
								<h6 class="text-right">Edit items?</h6>
							</div>
							<div class="col-xs-3">
								<button type="button" class="btn btn-default btn-sm btn-block">
									Update cart
								</button>
							</div>
						</div>
					</div>
				</div>
				<div class="panel-footer">
					<div class="row text-center">
						<div class="col-xs-9">
							<h4 class="text-right">Total <strong>$50.00</strong></h4>
						</div>
						<div class="col-xs-3">
								<%= link_to "Checkout", checkout_path, class:"btn btn-success btn-block" %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
  <% @users.each do |user| %>
    <li><%= user.first_name %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<div class="container">

<div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
		<form role="form">
			<h2>Please Sign Up <small>It's free and always will be.</small></h2>
			<hr class="colorgraph">
			<div class="row">
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="form-group">
              <%= f.text_field :first_name, class:"form-control input-lg",placeholder:"First Name"%>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="form-group">

              <%= f.text_field :last_name, class:"form-control input-lg",placeholder:"Last Name"%>

					</div>
				</div>
			</div>

			<div class="form-group">
        <%= f.text_field :email, class:"form-control input-lg",placeholder:"Email Address"%>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="form-group">
                <%= f.password_field :password, class:"form-control input-lg",placeholder:"Password" %>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="form-group">
                <%= f.password_field :password_confirmation, class:"form-control input-lg",placeholder:"Password Confirmation" %>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-4 col-sm-3 col-md-3">
					<span class="button-checkbox">
						<button type="button" class="btn" data-color="info" tabindex="7">I Agree</button>
                        <input type="checkbox" name="t_and_c" id="t_and_c" class="hidden" value="1">
					</span>
				</div>
				<div class="col-xs-8 col-sm-9 col-md-9">
					 By clicking <strong class="label label-primary">Register</strong>, you agree to the <a href="#" data-toggle="modal" data-target="#t_and_c_m">Terms and Conditions</a> set out by this site, including our Cookie Use.
				</div>
			</div>

			<hr class="colorgraph">
			<div class="row">
				<div class="col-xs-12 col-md-6"><%= f.submit "Register", class:"btn btn-primary btn-block btn-lg" %></div>
				<div class="col-xs-12 col-md-6"><%= link_to "Log In", login_path, class:"btn btn-success btn-block btn-lg" %></div>
			</div>
		</form>
	</div>
</div>
<!-- Modal -->
<div class="modal fade" id="t_and_c_m" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h4 class="modal-title" id="myModalLabel">Terms & Conditions</h4>
			</div>
			<div class="modal-body">
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" data-dismiss="modal">I Agree</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
</div>
<% end %>